server:
  port: 9000
logging:
  level:
    root: info
    #    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: trace
    #    org.springframework.security: debug
    org.springframework.security.web.FilterChainProxy: trace # ???????
    org.springframework.security.web.access.ExceptionTranslationFilter: trace #????

