server:
  port: 9000
spring:
  application:
    name: oauth2-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: test
    password: root
  jpa:
    database: MySQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  redis:
    database: 1
    host: localhost
    port: 6379
logging:
  level:
    root: info
    org.springframework.security.web.FilterChainProxy: trace
    org.springframework.security.web.access.ExceptionTranslationFilter: trace
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
